baseURL = 'https://sjs851009.github.io/my-hugo-site/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[menu]
  [[menu.menu]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
